gsap.timeline()
    .from('#logo_ifpoa', .2, { opacity: 0, x: -50, ease: Expo.easeInOut })
    .from('.navegas', .2, { opacity: 0, x: 100, ease: Expo.easeInOut })
    .from('.iti', .4, { opacity: 0, x: -50, ease: Expo.easeInOut })
    .from('#explicacao', .4, { opacity: 0, x: -25, ease: Expo.easeInOut })
    .from('#esquerda_col', .4, { opacity: 0, x: -25, ease: Expo.easeInOut })
    .from('#direita_col', .4, { opacity: 0, x: 100, ease: Expo.easeInOut })
    .from('#topo_row', .4, { delay: -.1, opacity: 0, x: -25, ease: Expo.easeInOut })
    .from('#meio_row', .4, { opacity: 0, x: -25, ease: Expo.easeInOut })
    .from('#baixo_row', .4, { opacity: 0, x: -25, ease: Expo.easeInOut })